{% set name = "lumicks.pylake" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71c8d178e58398ca5c8c6e9525c8162a36283d6d8c436126297d7139e30cbe3d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10,<4
    - numpy >=1.24,<2
    - matplotlib-base >=3.8
    - h5py >=3.4,<4
    - pytest >=3.5
    - scipy >=1.9,<2
    - tifffile >=2022.7.28
    - tabulate >=0.8.8,<0.9
    - cachetools >=3.1
    - deprecated >=1.2.8
    - scikit-learn >=0.18.0
    - scikit-image >=0.17.2
    - tqdm >=4.27.0
    - notebook >=7
    - ipywidgets >=7.0.0
    - jupyter_client >=8
    - ipympl >=0.9.3  # Needed for mpl 3.8 compatibility
test:
  imports:
    - lumicks.pylake
    - lumicks.pylake.tests
  requires:
    - pytest
  commands:
    - python -c "import lumicks.pylake as lk; import sys; sys.exit(lk.pytest())"

about:
  home: https://github.com/lumicks/pylake
  license: Apache-2.0
  license_file: license.md
  summary: Data analysis tools for Lumicks Bluelake
  dev_url: https://github.com/lumicks/pylake

extra:
  recipe-maintainers:
    - dean0x7d
    - JoepVanlier
    - rpauszek
    - tobiasjj
