{% set name = "lumicks.pylake" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 180df83b0fb71bb3670f443f3e4506f1867f6156636d763cabb2393a4efea113

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.6,<4
    - numpy >=1.20,<2
    - matplotlib-base >=2.2
    - h5py >=3.0,<4
    - pytest >=3.5
    - scipy >=1.1,<2
    - tifffile >=2019.7.26
    - tabulate ==0.8.6
    - opencv >=3.0
    - ipywidgets >=7.0.0
    - cachetools >=3.1
    - deprecated >=1.2.8
    - scikit-learn >=0.18.0
    - scikit-image >=0.17.2

test:
  imports:
    - lumicks.pylake
    - lumicks.pylake.tests
  requires:
    - pytest
  commands:
    - python -c "import lumicks.pylake as lk; import sys; sys.exit(lk.pytest())"

about:
  home: https://github.com/lumicks/pylake
  license: Apache-2.0
  license_file: license.md
  summary: Data analysis tools for Lumicks Bluelake
  dev_url: https://github.com/lumicks/pylake

extra:
  recipe-maintainers:
    - dean0x7d
    - onnodb
    - JoepVanlier
