{% set name = "lumicks.pylake" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70ba5120775de787f9eb2900af8a7f5ba1cec8bb6b3b18642ceedbefef28373f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.6,<4
    - numpy >=1.24,<2
    - matplotlib-base >=3.5
    - h5py >=3.4,<4
    - pytest >=3.5
    - scipy >=1.9,<2
    - tifffile >=2020.9.30
    - tabulate >=0.8.8,<0.9
    - cachetools >=3.1
    - deprecated >=1.2.8
    - scikit-learn >=0.18.0
    - scikit-image >=0.17.2
    - tqdm >=4.27.0
    - notebook >=4.4.1,<7
    - ipywidgets >=7.0.0
    - jupyter_client <8
    - pyzmq <25
test:
  imports:
    - lumicks.pylake
    - lumicks.pylake.tests
  requires:
    - pytest
  commands:
    - python -c "import lumicks.pylake as lk; import sys; sys.exit(lk.pytest())"

about:
  home: https://github.com/lumicks/pylake
  license: Apache-2.0
  license_file: license.md
  summary: Data analysis tools for Lumicks Bluelake
  dev_url: https://github.com/lumicks/pylake

extra:
  recipe-maintainers:
    - dean0x7d
    - JoepVanlier
    - rpauszek
    - tobiasjj
