{% set name = "lumicks.pylake" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92216307e382a169be1983519b7c23e3f32a3c001d45ba74e74141fdb8ef09bf

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6,<4
    - numpy >=1.14,<2
    - matplotlib >=2.2,<3
    - h5py >=2.8,<3
    - tifffile >=0.15,<1.0
    - pytest >=3.5,<4

test:
  imports:
    - lumicks.pylake
    - lumicks.pylake.tests

about:
  home: https://github.com/lumicks/pylake
  license: Apache 2.0
  license_file: license.md
  summary: 'Data analysis tools for Lumicks Bluelake'
  dev_url: https://github.com/lumicks/pylake

extra:
  recipe-maintainers:
    - dean0x7d
    - onnodb
