travis:
  secure:
    BINSTAR_TOKEN: EsSmeAw2SFabHl1LXnT8PGPSxZRkiaQB6r55EDTjBs408QO7SNGCWYbbc47Yv1KFGyj2kGU/B3fn7zGYSy16Ej1a+OoWcCHG0bqp85bWWGYbuwGjR5Pkb2PsZBg6SoaFecHATP09te1oFcrHrvJprQCYPwCB+zfJiI8EEXTjItEiK8xCUlxASHhCt4QQ4h4ddi/BY77dhv2gp/Np8JKJr2oMUvS/PUlkm/aDafRltcMniagLaE3J3xLwXOlnl2L0BBhfTYTpMMFcUJnA6zMopxozppeC/f3/NR23JvGNI14jSkfbKetJcgZkhVesP2OxaBVhdHQoDvlNux8keDDiEMslV8mwuozDrM2N6CMsA2+rL8Mibu9xCgXYAwHg9Gn7x7mSlJgV+HKixkvy1lUeIFORKGmN9N5aVZllmhoYPQL9XOgeWG9l+Por6mKDfOmYEj5c6oTQQoJRzfuhk9kjxe79lKzVmnShL6M5va1dMuqVCURCQsBpvLJnWV4pGWbr5DvwOWk4PHhpYJ6UZO6v5ekoYUh1cbW53OAXSEFjmG38ljTwMqR9g+sNpz23o0CJnpuh8eQpHQsK1ju6UrMonU3tfnzNKw0mQ1PNervWMWqQEWgRvXsEV86XkOs3VzgMkrMX59xiMB2WoCHGk8pTvwpbfVk7Dpbm2PQF5TZ6+Vc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
