travis:
  secure:
    BINSTAR_TOKEN: pYU9pIY6CyvQMpV4dkHOugkNxBpO/ONeSznVn5Baf+hFFBLVwfEZE4PpFbStd1NW+ra/taYf8Jfyl1i1cHzX8dXHxLwk38mBYq/NpqVabIb5Q683EFxo96oIJXcnt1b50DOUhlklsCRnc39M6sr574UjgwWJjLdStr9bnehdL1MV0MoPkAdBOCmFQjiu1zUfe2dHwH9e+lSPPv5+1xv0FlYHORqSaUEomDvlkeneW1regpL4zzlJop88mHGtpqeU6OsH/VtUl1rU4yx4QCQI0dzcRSdD0HoSxF4h7n/ebXP7yv1bv5PQzkUb41RvxMw5ppw3/IcF2/ojzDS2Vl2u8oyVG8XmUAGQ0UogkuO8RdxRVU+UIrOaR8pgOkZ0rp1GlilCAx/XcSbEKAwWLiyjQ5Detr9oIXl8bgipfqxlXomt2oxvUQ1DUBt5b8ZdeFd80t3zutmq+iYYW3XvS5Cgi8iuDS7SQZ9KQjEdtjI1z83kCCAJNlV2lu4Ztea663MxDmQ+ZjNoiS6EXRzfcsYOeuyhCUJjCF7A1sntipztvaOBr9h9lYunVoo2peseE9m707DuIuh41U3myxorHjK7m/CsasBiQg/eYkjdyYNqg5dAaECoVjWlZkzBSTKuDeTLujNiDsyXPn3RUDdjma4gnjVc2ZwZro+Xz7Orgt0p6J0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
